### ISSUE TITLE
Issue #01 - Wiki Home Page

### ISSUE THREAD

**Issue by keginzburg** [ShawnaEHartley/castlebnb#1]
# Wiki Home Page
- [X] Is the first page you see upon entering the wiki
- [X] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [X] All links in the right sidebar should contain each wiki page and link to the correct page
- [X] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [X] all links route the correct page

## Comments
1. Hey Shawna, your Welcome Page is looking great. You just need two small fixes. First, be sure to add either numbering or bullet points next to each page's link on your Welcome Page. Second, I know we're still adding our last few Design Documents, but be sure to add Placeholder Pages for them for now. That way, you can just edit them the night we begin working on them.
2. Ultimately, good work! Feel free to close this issue once you've made the above changes. Thanks.

**Comment by ShawnaEHartley** [comment]
Should I attempt to set up the live page via Render now or wait until we do that as a group?

**Comment by keginzburg** [comment]
This looks great!
