### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [ShawnaEHartley/castlebnb#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table's name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
1. I would consider taking out your `has_many listings` association for your `Users` table. That only applies if you reach your Bonus of allowing Users to Create Listings.
2. _While you're not incorporating Create Listings functionality initially (open to change down the line), I would be wary of providing your `Listings` a `lister_id`. You'll have to be careful with this when creating your seeds. Just something to keep track of._
3. You could store your images as entries in an `Images` table, but we will opt to use AWS for image storage so that table can be nixed. We'll talk more about this later.
4. For your tables, your foreign keys should reference tables, not the same foreign key (eg.`listing_id` references `listings` instead of `listing_id` references `listing_id`).
5. Your Reservations should also `belongs_to` a listing.
6. Right now, your `Reviews` table keeps track of a single `rating`. AirBnb employs a system for reviewers to rate a listing on its **Cleanliness, Accuracy, Communication, Location, Check-in, and Value**. I would incorporate all of these as separate columns in your reviews table.
7. Additionally, should we add a unique composite index between our `[listing_id, user_id]` in our Reviews table. Maybe we want to limit how many reviews a user can submit to a Listing? Not required, but food for thought.

Awesome work! Once you've made these changes and noted things to keep an eye out for, feel free to close this Issue!

**Comment by ShawnaEHartley** [comment]
Made suggested changes pertaining to 1, 3-7 in the doc.
