### ISSUE TITLE
Issue #04 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [ShawnaEHartley/castlebnb#4]
# Sample State
- [X] State shape is flat!
- [X] State's keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
1. Awesome job! This looks solid. Only thing that should be removed is the `images` slice of state under `entities`. Again, we'll discuss later how to associate images to a listing via AWS and not a separate table. Otherwise, feel free to close this Issue once you've seen it and made that small change.

**Comment by ShawnaEHartley** [comment]
I changed that and will note AWS storage for images.
